name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - ".git**"
  pull_request:

jobs:
  codeql-sast:
    name: CodeQL SAST scan
    uses: alphagov/govuk-infrastructure/.github/workflows/codeql-analysis.yml@main
    permissions:
      security-events: write

  dependency-review:
    name: Dependency Review scan
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main

  lint:
    uses: ./.github/workflows/lint.yml

  prettier:
    uses: ./.github/workflows/prettier.yml

  run-playwright-tests:
    needs:
      - lint
      - prettier
    uses: ./.github/workflows/playwright.yml

  vitest:
    needs:
      - lint
      - prettier
    uses: ./.github/workflows/vitest.yml

  release:
    needs:
      - vitest
      - run-playwright-tests
    permissions:
      contents: write
    uses: alphagov/govuk-infrastructure/.github/workflows/publish-npm-package.yml@main
    with:
      deploy_to_github_pages: true
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.ALPHAGOV_NPM_AUTOMATION_TOKEN }}
